name 'bcf_nginx'
maintainer 'Matthew Day'
maintainer_email 'matt@unlimitedday.com'
license 'All Rights Reserved'
description 'Installs/Configures nginx'
long_description 'Installs/Configures nginx'
version '1.0.0'
chef_version '>= 13.0'
